version: '3.8'

services:
  frontend:
    image: cob-service-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL = http://localhost:5001
    networks:
      - cob-service
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        max_replicas_per_node: 1
    depends_on:
      - backend

  backend:
    image: cob-service-backend:latest
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://mongoadmin:secret@db:27017/submission_management_db?authSource=admin
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_DEBUG=0
    networks:
      - cob-service
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    networks:
      - cob-service
    volumes:
      - mongo_data:/data/db
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  cob-service:
    driver: overlay
    attachable: true

volumes:
  mongo_data:
    driver: local